const result = {
  success: true,
  data: {
    categories: [
      { id: "7", name: "CAMPUS BOYS" },
      { id: "12", name: "Campus General" },
      { id: "10", name: "Campus Girls" },
      { id: "13", name: "Campus Girls parallel" },
      { id: "5", name: "GENERAL" },
      { id: "3", name: "HIGH SCHOOL" },
      { id: "4", name: "HIGHER SEC" },
      { id: "11", name: "JUNIOR" },
      { id: "1", name: "LOWER PRIMARY" },
      { id: "6", name: "SENIOR" },
      { id: "2", name: "UPPER PRIMARY" },
    ],
    allPrograms: [
      {
        id: "527",
        name: "ELOCUTION ENGLISH",
        categoryId: "3",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "528",
        name: "PROJECT",
        categoryId: "5",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "529",
        name: "COLLAGE",
        categoryId: "5",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "530",
        name: "NASHEEDA",
        categoryId: "5",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "532",
        name: "FAMILY MAGAZINE",
        categoryId: "5",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "533",
        name: "MAPPILAPPATTU",
        categoryId: "7",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "534",
        name: "MADHU GANAM",
        categoryId: "7",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "535",
        name: "ELOCUTION (MALAYALAM)",
        categoryId: "7",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "536",
        name: "ELOCUTION (ENGLISH)",
        categoryId: "7",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "537",
        name: "ESSAY WRITING (MALAYALAM)",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "538",
        name: "ESSAY WRITING (ENGLISH)",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "539",
        name: "STORY WRITING (MALAYALAM)",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "540",
        name: "POEM MAKING (MALAYALAM)",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "541",
        name: "POEM MAKING (ENGLISH)",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "542",
        name: "PENCIL DRAWING",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "543",
        name: "WATER COLOURING",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "544",
        name: "QUIZ",
        categoryId: "12",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "545",
        name: "BOOK TEST",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "547",
        name: "E POSTER",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "548",
        name: "VLOG",
        categoryId: "12",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "550",
        name: "DEBATE",
        categoryId: "7",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "551",
        name: "CAMPUS MAGAZINE",
        categoryId: "12",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "552",
        name: "DPR PRESENTATION",
        categoryId: "12",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "553",
        name: "CAPTURE THE FLAG",
        categoryId: "12",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "554",
        name: "LANGUAGE PRO",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "555",
        name: "ONLINE QUIZ",
        categoryId: "7",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "556",
        name: "ESSAY WRITING (MALAYALAM)",
        categoryId: "10",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "557",
        name: "ESSAY WRITING (ENGLISH)",
        categoryId: "10",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "558",
        name: "STORY WRITING (MALAYALAM)",
        categoryId: "10",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "559",
        name: "STORY WRITING (ENGLISH)",
        categoryId: "10",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "560",
        name: "POEM MAKING (MALAYALAM)",
        categoryId: "10",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "561",
        name: "POEM MAKING (ENGLISH)",
        categoryId: "10",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "562",
        name: "PENCIL DRAWING",
        categoryId: "10",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "563",
        name: "WATER COLOURING",
        categoryId: "10",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "564",
        name: "CALLIGRAPHY (ARABIC)",
        categoryId: "10",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "565",
        name: "BOOK TEST (ONLINE)",
        categoryId: "10",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "566",
        name: "QUIZ (ONLINE)",
        categoryId: "10",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "567",
        name: "ELOCUTION",
        categoryId: "1",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "568",
        name: "MADHU  SONG",
        categoryId: "1",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "569",
        name: "QUIZ",
        categoryId: "1",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "570",
        name: "STORY TELLING",
        categoryId: "1",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "571",
        name: "PENCIL DRAWING",
        categoryId: "1",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "572",
        name: "WATER COLOURING",
        categoryId: "1",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "573",
        name: "BHASHA KELI",
        categoryId: "1",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "574",
        name: "READING (MALAYALAM)",
        categoryId: "1",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "575",
        name: "READING (ARABI MALAYALAM)",
        categoryId: "1",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "576",
        name: "BOOK TEST",
        categoryId: "1",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "577",
        name: "PENCIL DRAWING(Girls)",
        categoryId: "1",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "578",
        name: "WATER COLOURING(Girls)",
        categoryId: "1",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "579",
        name: "MALAYALAM WRITING(Girls)",
        categoryId: "1",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "580",
        name: "ELOCUTION",
        categoryId: "2",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "581",
        name: "MAPPILAPPATTU",
        categoryId: "2",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "582",
        name: "STORY TELLING",
        categoryId: "2",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "583",
        name: "GANITHA KELI",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "584",
        name: "QUIZ",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "585",
        name: "PENCIL DRAWING",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "586",
        name: "WATER COLOURING",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "587",
        name: "STORY WRITING",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "589",
        name: "BOOK TEST",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "590",
        name: "SPELLING BEE",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "591",
        name: "PENCIL DRAWING(Girls)",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "592",
        name: "WATER COLOURING(Girls)",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "594",
        name: "STORY WRITING(Girls)",
        categoryId: "2",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "595",
        name: "ELOCUTION MALAYALAM",
        categoryId: "3",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "596",
        name: "MAPPILAPPATTU",
        categoryId: "3",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "597",
        name: "MADHU GANAM",
        categoryId: "3",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "598",
        name: "POEM RECITATION (ARABIC)",
        categoryId: "3",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "599",
        name: "POEM RECITATION (MALAYALAM)",
        categoryId: "3",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "600",
        name: "QUIZ",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "601",
        name: "STORY WRITING",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "602",
        name: "POEM MAKING",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "603",
        name: "PENCIL DRAWING",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "604",
        name: "WATER COLOURING",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "605",
        name: "POEM RECITATION (URDU)",
        categoryId: "3",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "606",
        name: "BOOK TEST",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "607",
        name: "ESSAY WRITING (MALAYALAM)",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "608",
        name: "NEWS READING",
        categoryId: "3",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "609",
        name: "CAPTION WRITING",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "610",
        name: "LANGUAGE GAME (ENGLISH)",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "611",
        name: "EMBROIDERY(Girls)",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "613",
        name: "PENCIL DRAWING(Girls)",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "614",
        name: "WATER COLOUR(Girls)",
        categoryId: "3",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "615",
        name: "STORY WRITING(Girls)",
        categoryId: "3",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "616",
        name: "POEM MAKING(Girls)",
        categoryId: "3",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "617",
        name: "ELOCUTION",
        categoryId: "4",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "618",
        name: "MAPPILAPPATTU",
        categoryId: "4",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "619",
        name: "BAKTHI GANAM",
        categoryId: "4",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "620",
        name: "STORY WRITING",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "621",
        name: "POEM MAKING",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "622",
        name: "ESSAY WRITING (MALAYALAM)",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "623",
        name: "ESSAY WRITING (ENGLISH)",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "624",
        name: "QUIZ",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "625",
        name: "PENCIL DRAWING",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "626",
        name: "WATER COLOURING",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "627",
        name: "BOOK TEST",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "628",
        name: "NEWS WRITING",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "630",
        name: "CALLIGRAPHY (ARABIC)",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "631",
        name: "POEM RECITATION (URDU)",
        categoryId: "4",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "632",
        name: "CALLIGRAPHY ARABIC(Girls)",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "633",
        name: "BOOK TEST(Girls)",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "634",
        name: "STORY WRITING(Girls)",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "635",
        name: "POEM MAKING(Girls)",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "636",
        name: "MAPPILAPPATTU",
        categoryId: "11",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "637",
        name: "ELOCUTION (MALAYALAM)",
        categoryId: "11",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "638",
        name: "ELOCUTION (ARABIC)",
        categoryId: "11",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "639",
        name: "ELOCUTION (ENGLISH)",
        categoryId: "11",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "640",
        name: "POEM MAKING",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "641",
        name: "STORY WRITING",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "642",
        name: "BOOK TEST",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "643",
        name: "ESSAY WRITING (MALAYALAM)",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "644",
        name: "ESSAY WRITING (ARABIC)",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "645",
        name: "MUDRAVAKYA RACHANA",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "646",
        name: "MADHU GANA RACHANA",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "647",
        name: "QUIZ",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "648",
        name: "TRANSLATION (ARABIC)",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "649",
        name: "CALLIGRAPHY (ARABIC)",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "651",
        name: "SOCIAL TEXT",
        categoryId: "11",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "652",
        name: "SAHITYA SAMVADAM",
        categoryId: "11",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "653",
        name: "HADEES MUSABAQA",
        categoryId: "11",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "654",
        name: "VIPLAVAGANA RACHANA",
        categoryId: "5",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "655",
        name: "MAPPILAPPATT RACHANA",
        categoryId: "5",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "656",
        name: "ESSAY WRITING (MALAYALAM)",
        categoryId: "13",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "657",
        name: "ESSAY WRITING (ENGLISH)",
        categoryId: "13",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "658",
        name: "STORY WRITING (MALAYALAM)",
        categoryId: "13",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "659",
        name: "STORY WRITING (ENGLISH)",
        categoryId: "13",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "660",
        name: "POEM MAKING (MALAYALAM)",
        categoryId: "13",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "661",
        name: "POEM MAKING (ENGLISH)",
        categoryId: "13",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "662",
        name: "PENCIL DRAWING",
        categoryId: "13",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "663",
        name: "WATER COLOURING",
        categoryId: "13",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "664",
        name: "CALLIGRAPHY (ARABIC)",
        categoryId: "13",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "665",
        name: "BOOK TEST (ONLINE)",
        categoryId: "13",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "667",
        name: "MAPPILAPPATTU",
        categoryId: "6",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "668",
        name: "ELOCUTION (MALAYALAM)",
        categoryId: "6",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "669",
        name: "ELOCUTION (ENGLISH)",
        categoryId: "6",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "670",
        name: "POEM MAKING",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "671",
        name: "STORY WRITING",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "672",
        name: "BOOK TEST",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "673",
        name: "ESSAY WRITING (MALAYALAM)",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "674",
        name: "ESSAY WRITING (ENGLISH)",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "675",
        name: "MADHU GANA RACHANA",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "676",
        name: "QUIZ",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "677",
        name: "FEATURE WRITING",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "678",
        name: "SOCIAL TEXT",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "680",
        name: "POEM MAKING (ENGLISH)",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "681",
        name: "TRANSLATION (ENGLISH)",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "682",
        name: "POSTER DESIGNING",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "683",
        name: "DIGITAL ILLUSTRATION",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "684",
        name: "E POSTER",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "685",
        name: "MAGAZINE LAYOUT",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "686",
        name: "ELOCUTION (URDU)",
        categoryId: "6",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "687",
        name: "HAMD (URDU)",
        categoryId: "6",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "688",
        name: "POEM RECITATION (ENGLISH)",
        categoryId: "6",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "689",
        name: "MUSHA'ARA ALFIYYA",
        categoryId: "6",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "690",
        name: "ESSAY WRITING (URDU)",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "691",
        name: "MUDRAVAKYA RACHANA",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "692",
        name: "SPOT MAGAZINE",
        categoryId: "5",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "693",
        name: "DUFF",
        categoryId: "5",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "694",
        name: "ARABANA",
        categoryId: "5",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "695",
        name: "GROUP SONG  (CATEGORY-A)",
        categoryId: "5",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "696",
        name: "GROUP SONG  (CATEGORY-B)",
        categoryId: "5",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "697",
        name: "MOULID RECITATION",
        categoryId: "5",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "698",
        name: "QASEEDA RECITATION",
        categoryId: "5",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "699",
        name: "VIPLAVA GANAM",
        categoryId: "5",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "700",
        name: "CHUMAREZHUTH",
        categoryId: "5",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "701",
        name: "MALAPPATTU",
        categoryId: "5",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "702",
        name: "RISALA QUIZ",
        categoryId: "5",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "703",
        name: "QAWWALI",
        categoryId: "5",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "704",
        name: "SOCIAL STORY",
        categoryId: "5",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "706",
        name: "JOURNAL ART (Girls)",
        categoryId: "1",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "708",
        name: "SUDOKU",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "709",
        name: "ORIGAMI(Girls)",
        categoryId: "2",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "710",
        name: "REEL MAKING",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "711",
        name: "DIGITAL PAINTING",
        categoryId: "4",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "714",
        name: "POLITICAL DEBATE",
        categoryId: "6",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "715",
        name: "DIGITAL PAINTING",
        categoryId: "6",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "716",
        name: "AI PROMPTING",
        categoryId: "7",
        eventOrder: 0,
        programType: "Off Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "717",
        name: "IDEATHON",
        categoryId: "12",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "718",
        name: "AI POEM MAKING",
        categoryId: "11",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
      {
        id: "719",
        name: "REEL MAKING",
        categoryId: "11",
        eventOrder: 0,
        programType: "Stage",
        scheduledStart: null,
        scheduledEnd: null,
      },
    ],
    templates: [
      {
        id: "8bkVn5DmFmubcz0haKU7",
        name: "Temp30",
        file_path: "templates/1754026854754_model 1.png",
        downloadURL:
          "https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F1754026854754_model%201.png?alt=media&token=36fbe7ee-9734-4bb0-865e-2c805e65edcd",
        createdAt: { _seconds: 1754026863, _nanoseconds: 587000000 },
        malayalamEnabled: false,
        template_html:
          "<style>\n\n@font-face {\n    font-family: 'FN ANUPAMA';\n    src: local('FN-ANUPAMA'),\n        url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754018421082_FN-ANUPAMA.woff2?alt=media&token=a627eaa4-d16b-4ac6-bc6b-b9b4e576be3b') format('woff2'),\n       ;\n    font-weight: bold;\n    font-style: normal;\n    font-display: swap;\n}\n\n@font-face {\n    font-family: 'Playfair Display';\n    src: local('Playfair Display Italic'), local('PlayfairDisplay-Italic'),\n        url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754019844758_PlayfairDisplay-Italic.woff2?alt=media&token=a3d83668-cb0b-48b8-89e0-8c76b30202f2') format('woff2');\n    font-weight: normal;\n    font-style: italic;\n    font-display: swap;\n}\n\n@font-face {\n    font-family: 'Space Grotesk';\n    src: local('Space Grotesk Light'), local('SpaceGrotesk-Light'),\n        url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754019875095_SpaceGrotesk-Light.woff2?alt=media&token=ef4ae07e-3b93-4314-bb0c-7a6650035595') format('woff2');\n    font-weight: 300;\n    font-style: normal;\n    font-display: swap;\n}\n\n@font-face {\n    font-family: 'Space Grotesk';\n    src: local('Space Grotesk Medium'), local('SpaceGrotesk-Medium'),\n        url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754019862642_SpaceGrotesk-Medium.woff2?alt=media&token=ffc798ab-9cac-4869-9c73-7fd8c02bd158') format('woff2');\n    font-weight: 500;\n    font-style: normal;\n    font-display: swap;\n}\n\n\n\n/* --- SETUP --- */\n@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&family=Manjari:wght@400;700&family=Montserrat:wght@400;700&family=Dancing+Script:wght@400;700&family=Pacifico&family=Kalam:wght@400;700&display=swap');\n.container { position: relative; width: 100%; height: 100%; font-family: 'Roboto', sans-serif; box-sizing: border-box;   }\n.lang-ml .container { font-family: 'Manjari', sans-serif; }\n\n/* --- FONT STYLES --- */\n.category-block {\n    font-size: 80px;\n    letter-spacing: 2px;\n    font-family: 'Playfair Display'; \n    color: #21ffaa ;\n    font-style: italic;\n    margin-bottom: 2px;\n        letter-spacing: -2px;\n\n}\n.program-block {\n    font-size: 160px;\n    font-family: 'FN ANUPAMA';\n    font-weight: normal;\n    line-height: 0.8;\n    color: #ffffff;\n    margin-bottom: 80px;\n    max-width: 634px;\n    letter-spacing: 2px;\n}\n.winner-block .name { \n    font-size: 90px; \n    line-height: 0.8; \n    font-family: 'Space Grotesk';\n    font-weight: 500;\n    color: #ffffff; \n    margin: 0 0 8px 0; \n}\n.winner-block .district { \n    font-size: 40px; \n    font-weight: 300; \n    font-family: 'Space Grotesk';\n    color: #ffffff; \n    opacity: 1; \n    margin: 0; \n}\n\n/* --- PRIZE IMAGE CONTAINER --- */\n.prize-image {\n    width: 600px;\n    height: 120px;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    flex-shrink: 0;\n    margin-right: -80px;\n    position: relative;\n}\n\n.prize-image::before {\n    content: '';\n    width: 80px;\n    height: 80px;\n    background-size: contain;\n    background-repeat: no-repeat;\n    background-position: center;\n    filter: drop-shadow(4px 4px 8px rgba(0,0,0,0.3));\n}\n\n/* Prize-specific images - Replace these URLs with your Firebase Storage URLs */\n.winner-block[data-prize=\"1\"] .prize-image::before {\n    width:\t600px;\n    height: 100px;\n    background-image: url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F001.png?alt=media&token=62b66bfb-e784-4405-9d54-e7b99dbb4869');\n}\n\n.winner-block[data-prize=\"2\"] .prize-image::before {\n    width:  600px;\n    height: 100px;\n    background-image: url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F002.png?alt=media&token=2984da4b-115a-42e6-9033-33d5170d008c');\n}\n\n.winner-block[data-prize=\"3\"] .prize-image::before {\n    width: 600px;\n    height: 100px;\n    background-image: url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F003.png?alt=media&token=bf564eea-ed64-43c5-8f3b-5d571b885786');\n}\n\n/* Fallback: If you want to use the same image for all prizes, uncomment this:\n.prize-image::before {\n    background-image: url('https://firebasestorage.googleapis.com/v0/b/edavannapparadivision.firebasestorage.app/o/images%2Fdefault-prize.png?alt=media&token=YOUR_TOKEN');\n}\n*/\n\n/* --- LAYOUT --- */\n.left-section {\n    position: absolute; top: 33.72%; left: 0%;\n    width: 37.04%;\n    text-align: left;\n}\n\n.right-section {\n    position: absolute; top: 51.7877%; left: 0%;\n     width: 50.04%;\n\n}\n\n.lang-ml .left-section {\n    top: 14.81%;\n    left: 5.56%;\n}\n.lang-ml .category-block {\n    font-family: 'Kalam', cursive;\n}\n\n.title-area { margin-bottom: 100px; }\n.winners-section { display: flex; flex-direction: column; gap:40px; }\n.winner-block { display: flex; align-items: center; text-align: left; }\n\n/* Dark background for preview */\n\n</style>\n\n<div class=\"container\">\n    <div class=\"left-section\" data-editable=\"true\" data-name=\"Program Section\">\n        <div class=\"category-block\">{{categoryName}}</div>\n        <div class=\"program-block\">{{programName}}</div>\n    </div>\n\n    <div class=\"right-section\" data-editable=\"true\" data-name=\"Winners Section\">\n        <div class=\"winners-section\">\n            {{#each winners}}\n            <div class=\"winner-block\" data-prize=\"{{prize}}\">\n                <div class=\"prize-image\"></div>\n                <div class=\"winner-info\">\n                    <p class=\"name\">{{name}}</p>\n                    <p class=\"district\">{{district}}</p>\n                </div>\n            </div>\n            {{/each}}\n        </div>\n    </div>\n</div>\n\n<script>\n// Sample data for preview\nconst winners = [\n    { prize: 1, name: \"Musadhiq\", district: \"Edavannapara\" },\n    { prize: 2, name: \"Mohammed Jauhar Op\", district: \"Vilayil\" },\n    { prize: 3, name: \"Sanah Kk\", district: \"Muthuvallur\" }\n];\n\n// Create preview HTML\nconst winnersHtml = winners.map(winner => `\n    <div class=\"winner-block\" data-prize=\"${winner.prize}\">\n        <div class=\"prize-image\"></div>\n        <div class=\"winner-info\">\n            <p class=\"name\">${winner.name}</p>\n            <p class=\"district\">${winner.district}</p>\n        </div>\n    </div>\n`).join('');\n\ndocument.querySelector('.winners-section').innerHTML = winnersHtml;\ndocument.querySelector('.program-block').textContent = \"ELOUCATION ENGLISH\";\ndocument.querySelector('.category-block').textContent = \"Senior\";\n</script>",
      },
      {
        id: "BB0SDjyRuw3zAZh1xn5m",
        name: "m1",
        file_path: "templates/1754022266508_m1.png",
        downloadURL:
          "https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F1754022266508_m1.png?alt=media&token=1fd5359d-d46a-494f-bfcb-1773a47f4c94",
        createdAt: { _seconds: 1754022272, _nanoseconds: 778000000 },
        malayalamEnabled: false,
        template_html:
          "<style>\n\n@font-face {\n    font-family: 'FN ANUPAMA';\n    src: local('FN-ANUPAMA'),\n        url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754018421082_FN-ANUPAMA.woff2?alt=media&token=a627eaa4-d16b-4ac6-bc6b-b9b4e576be3b') format('woff2'),\n       ;\n    font-weight: bold;\n    font-style: normal;\n    font-display: swap;\n}\n\n@font-face {\n    font-family: 'Playfair Display';\n    src: local('Playfair Display Italic'), local('PlayfairDisplay-Italic'),\n        url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754019844758_PlayfairDisplay-Italic.woff2?alt=media&token=a3d83668-cb0b-48b8-89e0-8c76b30202f2') format('woff2');\n    font-weight: normal;\n    font-style: italic;\n    font-display: swap;\n}\n\n@font-face {\n    font-family: 'Space Grotesk';\n    src: local('Space Grotesk Light'), local('SpaceGrotesk-Light'),\n        url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754019875095_SpaceGrotesk-Light.woff2?alt=media&token=ef4ae07e-3b93-4314-bb0c-7a6650035595') format('woff2');\n    font-weight: 300;\n    font-style: normal;\n    font-display: swap;\n}\n\n@font-face {\n    font-family: 'Space Grotesk';\n    src: local('Space Grotesk Medium'), local('SpaceGrotesk-Medium'),\n        url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754019862642_SpaceGrotesk-Medium.woff2?alt=media&token=ffc798ab-9cac-4869-9c73-7fd8c02bd158') format('woff2');\n    font-weight: 500;\n    font-style: normal;\n    font-display: swap;\n}\n\n\n\n/* --- SETUP --- */\n@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&family=Manjari:wght@400;700&family=Montserrat:wght@400;700&family=Dancing+Script:wght@400;700&family=Pacifico&family=Kalam:wght@400;700&display=swap');\n.container { position: relative; width: 100%; height: 100%; font-family: 'Roboto', sans-serif; box-sizing: border-box;   }\n.lang-ml .container { font-family: 'Manjari', sans-serif; }\n\n/* --- FONT STYLES --- */\n.category-block {\n    font-size: 40px;\n    letter-spacing: 1px;\n    font-family: 'Playfair Display'; \n    color: #21ffaa ;\n    font-style: italic;\n    margin-bottom: 1px;\n        letter-spacing: -1px;\n\n}\n.program-block {\n    font-size: 80px;\n    font-family: 'FN ANUPAMA';\n    font-weight: normal;\n    line-height: 0.8;\n    color: #ffffff;\n    margin-bottom: 40px;\n    max-width: 317px;\n    letter-spacing: 1px;\n}\n.winner-block .name { \n    font-size: 45px; \n    line-height: 0.8; \n    font-family: 'Space Grotesk';\n    font-weight: 500;\n    color: #ffffff; \n    margin: 0 0 4px 0; \n}\n.winner-block .district { \n    font-size: 20px; \n    font-weight: 300; \n    font-family: 'Space Grotesk';\n    color: #ffffff; \n    opacity: 1; \n    margin: 0; \n}\n\n/* --- PRIZE IMAGE CONTAINER --- */\n.prize-image {\n    width: 300px;\n    height: 60px;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    flex-shrink: 0;\n    margin-right: -40px;\n    position: relative;\n}\n\n.prize-image::before {\n    content: '';\n    width: 40px;\n    height: 40px;\n    background-size: contain;\n    background-repeat: no-repeat;\n    background-position: center;\n    filter: drop-shadow(2px 2px 4px rgba(0,0,0,0.3));\n}\n\n/* Prize-specific images - Replace these URLs with your Firebase Storage URLs */\n.winner-block[data-prize=\"1\"] .prize-image::before {\n    width:\t300px;\n    height: 50px;\n    background-image: url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F001.png?alt=media&token=62b66bfb-e784-4405-9d54-e7b99dbb4869');\n}\n\n.winner-block[data-prize=\"2\"] .prize-image::before {\n    width:  300px;\n    height: 50px;\n    background-image: url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F002.png?alt=media&token=2984da4b-115a-42e6-9033-33d5170d008c');\n}\n\n.winner-block[data-prize=\"3\"] .prize-image::before {\n    width: 300px;\n    height: 50px;\n    background-image: url('https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F003.png?alt=media&token=bf564eea-ed64-43c5-8f3b-5d571b885786');\n}\n\n/* Fallback: If you want to use the same image for all prizes, uncomment this:\n.prize-image::before {\n    background-image: url('https://firebasestorage.googleapis.com/v0/b/edavannapparadivision.firebasestorage.app/o/images%2Fdefault-prize.png?alt=media&token=YOUR_TOKEN');\n}\n*/\n\n/* --- LAYOUT --- */\n.left-section {\n    position: absolute; top: 33.72%; left: 11.2%;\n    width: 37.04%;\n    text-align: left;\n}\n\n.right-section {\n    position: absolute; top: 51.7877%; left: 2.2%;\n     width: 50.04%;\n\n}\n\n.lang-ml .left-section {\n    top: 14.81%;\n    left: 5.56%;\n}\n.lang-ml .category-block {\n    font-family: 'Kalam', cursive;\n}\n\n.title-area { margin-bottom: 50px; }\n.winners-section { display: flex; flex-direction: column; gap:20px; }\n.winner-block { display: flex; align-items: center; text-align: left; }\n\n/* Dark background for preview */\n\n</style>\n\n<div class=\"container\">\n    <div class=\"left-section\" data-editable=\"true\" data-name=\"Program Section\">\n        <div class=\"category-block\">{{categoryName}}</div>\n        <div class=\"program-block\">{{programName}}</div>\n    </div>\n\n    <div class=\"right-section\" data-editable=\"true\" data-name=\"Winners Section\">\n        <div class=\"winners-section\">\n            {{#each winners}}\n            <div class=\"winner-block\" data-prize=\"{{prize}}\">\n                <div class=\"prize-image\"></div>\n                <div class=\"winner-info\">\n                    <p class=\"name\">{{name}}</p>\n                    <p class=\"district\">{{district}}</p>\n                </div>\n            </div>\n            {{/each}}\n        </div>\n    </div>\n</div>\n\n<script>\n// Sample data for preview\nconst winners = [\n    { prize: 1, name: \"Musadhiq\", district: \"Edavannapara\" },\n    { prize: 2, name: \"Mohammed Jauhar Op\", district: \"Vilayil\" },\n    { prize: 3, name: \"Sanah Kk\", district: \"Muthuvallur\" }\n];\n\n// Create preview HTML\nconst winnersHtml = winners.map(winner => `\n    <div class=\"winner-block\" data-prize=\"${winner.prize}\">\n        <div class=\"prize-image\"></div>\n        <div class=\"winner-info\">\n            <p class=\"name\">${winner.name}</p>\n            <p class=\"district\">${winner.district}</p>\n        </div>\n    </div>\n`).join('');\n\ndocument.querySelector('.winners-section').innerHTML = winnersHtml;\ndocument.querySelector('.program-block').textContent = \"ELOUCATION ENGLISH\";\ndocument.querySelector('.category-block').textContent = \"Senior\";\n</script>",
        dimensions: { width: 1500, height: 1500 },
      },
      {
        id: "O9YDxBRaksiTFRFOTdD3",
        name: "1",
        file_path: "templates/1753801542117_2160 sample.png",
        downloadURL:
          "https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F1753801542117_2160%20sample.png?alt=media&token=aa7c83c1-c8e0-45c3-8017-affc57a9f9ab",
        createdAt: { _seconds: 1753801550, _nanoseconds: 889000000 },
        malayalamEnabled: false,
        template_html:
          '<style>\n/* --- SETUP --- */\n@import url(\'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&family=Manjari:wght@400;700&family=Montserrat:wght@400;700&display=swap\');\n.container { position: relative; width: 100%; height: 100%; font-family: \'Roboto\', sans-serif; box-sizing: border-box; color: #ffffff; text-shadow: 0px 2px 8px rgba(0, 0, 0, 0.6); }\n.lang-ml .container { font-family: \'Manjari\', sans-serif; }\n/* --- FONT STYLES --- */\n.category-block { font-size: 24px; font-weight: 400; letter-spacing: 2px; text-transform: uppercase; font-family: \'Montserrat\', sans-serif; color: #ffffff; }\n.program-block { font-size: 61px; font-family: \'Montserrat\', sans-serif; font-weight: 700; line-height: 1.1; color: #ffffff; }\n.winner-block .name { font-size: 32px; font-weight: 700; line-height: 1.0; font-family: \'Montserrat\', sans-serif; color: #ffffff; margin: 0 0 4px 0; }\n.winner-block .district { font-size: 24px; font-weight: 400; font-family: \'Montserrat\', sans-serif; color: #ffffff; opacity: 0.8; margin: 0; }\n.prize-number { width: 45px; height: 45px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 24px; font-weight: 700; color: #333; text-shadow: none; flex-shrink: 0; margin-right: 20px; }\n/* --- LAYOUT --- */\n.content-block { position: absolute; top: 53.1586%; left: 62.2488%; width: 550px; text-align: left; display: flex; flex-direction: column; \n\n\n\n}\n.lang-ml .content-block { top: 162px; left: 241px; }\n.title-area { margin-bottom: 50px; }\n.winners-section { display: flex; flex-direction: column; gap: 15px; }\n.winner-block { display: flex; align-items: center; text-align: left; }\n/* Prize Number Colors */\n.winner-block[data-prize="1"] .prize-number { background: linear-gradient(135deg, #ffd700, #ffed4e); }\n.winner-block[data-prize="2"] .prize-number { background: linear-gradient(135deg, #c0c0c0, #e5e5e5); }\n.winner-block[data-prize="3"] .prize-number { background: linear-gradient(135deg, #cd7f32, #daa520); }\n</style>\n<div class="container">\n    <div class="content-block" data-editable="true" data-name="Content Block">\n        <div class="title-area">\n            <div class="program-block">{{programName}}</div>\n            <div class="category-block">{{categoryName}}</div>\n        </div>\n        <div class="winners-section">\n            {{#each winners}}\n            <div class="winner-block" data-prize="{{prize}}">\n                <div class="prize-number">{{prize}}</div>\n                <div class="winner-info">\n                    <p class="name">{{name}}</p>\n                    <p class="district">{{district}}</p>\n                </div>\n            </div>\n            {{/each}}\n        </div>\n    </div>\n</div>',
      },
      {
        id: "YDyh48KkTmpEEcoKmwKM",
        name: "15002",
        file_path: "templates/1753966416755_1500sample.png",
        downloadURL:
          "https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F1753966416755_1500sample.png?alt=media&token=3bf6e849-53a1-4522-aa70-c66bb4885b8d",
        createdAt: { _seconds: 1753966426, _nanoseconds: 65000000 },
        template_html:
          '<style>\n/* --- SETUP --- */\n@import url(\'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&family=Manjari:wght@400;700&family=Montserrat:wght@400;700&display=swap\');\n.container { position: relative; width: 100%; height: 100%; font-family: \'Roboto\', sans-serif; box-sizing: border-box; color: #ffffff; text-shadow: 0px 2px 8px rgba(0, 0, 0, 0.6); }\n.lang-ml .container { font-family: \'Manjari\', sans-serif; }\n/* --- FONT STYLES --- */\n.category-block { font-size: 24px; font-weight: 400; letter-spacing: 2px; text-transform: uppercase; font-family: \'Montserrat\', sans-serif; color: #ffffff; }\n.program-block { font-size: 61px; font-family: \'Montserrat\', sans-serif; font-weight: 700; line-height: 1.1; color: #ffffff; }\n.winner-block .name { font-size: 32px; font-weight: 700; line-height: 1.0; font-family: \'Montserrat\', sans-serif; color: #ffffff; margin: 0 0 4px 0; }\n.winner-block .district { font-size: 24px; font-weight: 400; font-family: \'Montserrat\', sans-serif; color: #ffffff; opacity: 0.8; margin: 0; }\n.prize-number { width: 45px; height: 45px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 24px; font-weight: 700; color: #333; text-shadow: none; flex-shrink: 0; margin-right: 20px; }\n/* --- LAYOUT --- */\n.content-block { position: absolute; top: 44.052%; left: 56.8%; width: 50.92%; text-align: left; display: flex; flex-direction: column; \n\n\n\n\n\n\n\n}\n.lang-ml .content-block { top: 15%; left: 22.31%; }\n.title-area { margin-bottom: 50px; }\n.winners-section { display: flex; flex-direction: column; gap: 15px; }\n.winner-block { display: flex; align-items: center; text-align: left; }\n/* Prize Number Colors */\n.winner-block[data-prize="1"] .prize-number { background: linear-gradient(135deg, #ffd700, #ffed4e); }\n.winner-block[data-prize="2"] .prize-number { background: linear-gradient(135deg, #c0c0c0, #e5e5e5); }\n.winner-block[data-prize="3"] .prize-number { background: linear-gradient(135deg, #cd7f32, #daa520); }\n</style>\n<div class="container">\n    <div class="content-block" data-editable="true" data-name="Content Block">\n        <div class="title-area">\n            <div class="program-block">{{programName}}</div>\n            <div class="category-block">{{categoryName}}</div>\n        </div>\n        <div class="winners-section">\n            {{#each winners}}\n            <div class="winner-block" data-prize="{{prize}}">\n                <div class="prize-number">{{prize}}</div>\n                <div class="winner-info">\n                    <p class="name">{{name}}</p>\n                    <p class="district">{{district}}</p>\n                </div>\n            </div>\n            {{/each}}\n        </div>\n    </div>\n</div>',
        malayalamEnabled: false,
      },
      {
        id: "gsFC1ToGoOR7HVtEewEY",
        name: "1080",
        file_path: "templates/1753904326394_sampletwmp2.png",
        downloadURL:
          "https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/templates%2F1753904326394_sampletwmp2.png?alt=media&token=8d8d05e4-a299-41d3-aaf2-b98928bb7f02",
        createdAt: { _seconds: 1753904334, _nanoseconds: 593000000 },
        malayalamEnabled: false,
        template_html:
          '<style>\n\n@font-face {\n    font-family: \'Thoriq\';\n    src: local(\'Thoriq Regular\'), local(\'Thoriq-Regular\'),\n        url(\'https://firebasestorage.googleapis.com/v0/b/edavannapparadivision.firebasestorage.app/o/fonts%2F1753001434784_Thoriq-Regular.woff2?alt=media&token=317d5e28-992c-4ff6-b52d-cbfcc024614c\') format(\'woff2\'),\n    ;\n    font-weight: normal;\n    font-style: italic;\n    font-display: swap;\n}\n\n\n@font-face {\n    font-family: \'Fractul\';\n    src: local(\'Fractul Light\'), local(\'Fractul-Light\'),\n        url(\'https://firebasestorage.googleapis.com/v0/b/edavannapparadivision.firebasestorage.app/o/fonts%2F1752995955600_Fractul-Light.woff2?alt=media&token=2f59f1aa-2209-4628-bce8-60008c021d5f\') format(\'woff2\'),\n      ;\n    font-weight: 300;\n    font-style: normal;\n    font-display: swap;\n}\n\n@font-face {\n    font-family: \'Thoriq Swash\';\n    src: local(\'Thoriq Swash Regular\'), local(\'ThoriqSwash-Regular\'),\n        url(\'https://firebasestorage.googleapis.com/v0/b/edavannapparadivision.firebasestorage.app/o/fonts%2F1752995438738_ThoriqSwash-Regular.woff2?alt=media&token=8f679779-a1a6-45bc-b346-bc0c5d850f57\') format(\'woff2\'),\n    ;\n    font-weight: normal;\n    font-style: italic;\n    font-display: swap;\n}\n\n\n/* Fractul Medium Font */\n@font-face {\n  font-family: \'Fractul\';\n  src: local(\'Fractul Medium\'), local(\'Fractul-Medium\'),\n       url(\'https://firebasestorage.googleapis.com/v0/b/edavannapparadivision.firebasestorage.app/o/fonts%2F1752963291937_Fractul-Medium.woff2?alt=media&token=5a460f67-2bc0-4e9b-ac47-55af43ca5b09\') format(\'woff2\');\n  font-weight: 500;\n  font-style: normal;\n  font-display: swap;\n}\n\n/* Fractul Regular Font */\n@font-face {\n  font-family: \'Fractul\';\n  src: local(\'Fractul Regular\'), local(\'Fractul-Regular\'),\n       url(\'https://firebasestorage.googleapis.com/v0/b/edavannapparadivision.firebasestorage.app/o/fonts%2F1752963309717_Fractul-Regular.woff2?alt=media&token=6a48a8b0-7c3e-4ace-bdad-0aa8c6f3356a\') format(\'woff2\');\n  font-weight: normal;\n  font-style: normal;\n  font-display: swap;\n}\n\n/* Bestie Seventy Font */\n@font-face {\n  font-family: \'Bestie Seventy\';\n  src: local(\'BestieSeventy\'),\n       url(\'https://firebasestorage.googleapis.com/v0/b/edavannapparadivision.firebasestorage.app/o/fonts%2F1752962760090_BestieSeventy.woff2?alt=media&token=0403075e-7e77-4dc8-8bb6-bcc9f5236185\') format(\'woff2\');\n  font-weight: normal;\n  font-style: normal;\n  font-display: swap;\n}\n\n/* --- SETUP --- */\n@import url(\'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&family=Manjari:wght@400;700&family=Montserrat:wght@400;700&family=Dancing+Script:wght@400;700&family=Pacifico&family=Kalam:wght@400;700&display=swap\');\n.container { position: relative; width: 100%; height: 100%; font-family: \'Roboto\', sans-serif; box-sizing: border-box;   }\n.lang-ml .container { font-family: \'Manjari\', sans-serif; }\n\n/* --- FONT STYLES --- */\n.category-block {\n    font-size: 40px;\n    font-weight: 700;\n    letter-spacing: 1px;\n    font-family: \'Thoriq\', serif; \n    color: #ffcc33 ;\n    font-style: italic;\n    transform: rotate(-2deg);\n    margin-bottom: 10px;\n}\n.program-block {\n    font-size: 29px;\n    font-family: \'Fractul\', sans-serif;\n    font-weight: normal;\n    line-height: 1.2;\n    color: #ffffff;\n    margin-bottom: 40px;\n}\n.winner-block .name { \n    font-size: 29px; \n    line-height: 0.8; \n    font-family: \'Fractul\', sans-serif;\n    font-weight: 500;\n    color: #ffffff; \n    margin: 0 0 4px 0; \n}\n.winner-block .district { \n    font-size: 20px; \n    font-weight: 300; \n    font-family: \'Fractul\', sans-serif;\n    color: #ffffff; \n    opacity: 1; \n    margin: 0; \n}\n\n/* --- PRIZE DOTS USING REAL HTML ELEMENTS --- */\n.prize-dots {\n    width: 80px;\n    height: 60px;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    flex-shrink: 0;\n    margin-right: 0px;\n    position: relative;\n}\n\n.dot {\n    width: 10px;\n    height: 10px;\n    border-radius: 50%;\n    background: #ffffff;\n    position: absolute;\n\n}\n\n/* Always show 3 dots, hide extra ones based on prize */\n.prize-dots .dot:nth-child(1) { left: 30px; top: 15px; }  /* Top dot for triangle */\n.prize-dots .dot:nth-child(2) { left: 24px; top: 27px; } /* Bottom left */\n.prize-dots .dot:nth-child(3) { left: 35px; top: 27px; } /* Bottom right */\n\n/* 1st place - only show middle dot, reposition it to center */\n.winner-block[data-prize="1"] .prize-dots .dot:nth-child(1) { left: 30px; top: 20px; width:17px; height:17px;}\n.winner-block[data-prize="1"] .prize-dots .dot:nth-child(2) { display: none; }\n.winner-block[data-prize="1"] .prize-dots .dot:nth-child(3) { display: none; }\n\n/* 2nd place - show 2 dots horizontally */\n.winner-block[data-prize="2"] .prize-dots .dot:nth-child(1) { left: 24px; top: 20px; }\n.winner-block[data-prize="2"] .prize-dots .dot:nth-child(2) { left: 35px; top: 20px; }\n.winner-block[data-prize="2"] .prize-dots .dot:nth-child(3) { display: none; }\n\n/* 3rd place - show all 3 dots in triangle (default positioning) */\n\n/* --- LAYOUT --- */\n.left-section {\n    position: absolute; top: 33.72%; left: 53.44%;\n    width: 37.04%;\n    text-align: left;\n}\n\n.right-section {\n    position: absolute; top: 51.7877%; left: 54.0091%;\n    width: 36.11%;\n\n\n}\n\n.lang-ml .left-section {\n    top: 14.81%;\n    left: 5.56%;\n}\n.lang-ml .category-block {\n    font-family: \'Kalam\', cursive;\n}\n\n.title-area { margin-bottom: 50px; }\n.winners-section { display: flex; flex-direction: column; gap:20px; }\n.winner-block { display: flex; align-items: center; text-align: left; }\n</style>\n\n<div class="container">\n    <div class="left-section" data-editable="true" data-name="Program Section">\n        <div class="category-block">{{categoryName}}</div>\n        <div class="program-block">{{programName}}</div>\n    </div>\n\n    <div class="right-section" data-editable="true" data-name="Winners Section">\n        <div class="winners-section">\n            {{#each winners}}\n            <div class="winner-block" data-prize="{{prize}}">\n                <div class="prize-dots">\n                    <div class="dot"></div>\n                    <div class="dot"></div>\n                    <div class="dot"></div>\n                </div>\n                <div class="winner-info">\n                    <p class="name">{{name}}</p>\n                    <p class="district">{{district}}</p>\n                </div>\n            </div>\n            {{/each}}\n        </div>\n    </div>\n</div>\n\n<script>\n// Sample data for preview\nconst winners = [\n    { prize: 1, name: "Musadhiq", district: "Edavannapara" },\n    { prize: 2, name: "Mohammed Jauhar Op", district: "Vilayil" },\n    { prize: 3, name: "Sanah Kk", district: "Muthuvallur" }\n];\n\n// Create preview with real HTML dots\nconst winnersHtml = winners.map(winner => `\n    <div class="winner-block" data-prize="${winner.prize}">\n        <div class="prize-dots">\n            <div class="dot"></div>\n            <div class="dot"></div>\n            <div class="dot"></div>\n        </div>\n        <div class="winner-info">\n            <p class="name">${winner.name}</p>\n            <p class="district">${winner.district}</p>\n        </div>\n    </div>\n`).join(\'\');\n\ndocument.querySelector(\'.winners-section\').innerHTML = winnersHtml;\ndocument.querySelector(\'.program-block\').textContent = "Family Magazine";\ndocument.querySelector(\'.category-block\').textContent = "General";\n</script>',
      },
    ],
    fonts: [
      {
        id: "1W9yX99GOka5BS97ngc9",
        name: "space-light",
        file_path: "fonts/1754019875095_SpaceGrotesk-Light.woff2",
        downloadURL:
          "https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754019875095_SpaceGrotesk-Light.woff2?alt=media&token=ef4ae07e-3b93-4314-bb0c-7a6650035595",
        createdAt: { _seconds: 1754019876, _nanoseconds: 597000000 },
      },
      {
        id: "Ji3nBT8rzocUT1pt7z8l",
        name: "playfair-italic",
        file_path: "fonts/1754019844758_PlayfairDisplay-Italic.woff2",
        downloadURL:
          "https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754019844758_PlayfairDisplay-Italic.woff2?alt=media&token=a3d83668-cb0b-48b8-89e0-8c76b30202f2",
        createdAt: { _seconds: 1754019847, _nanoseconds: 267000000 },
      },
      {
        id: "hL9gdUzUatgmkOc87jua",
        name: "anupama",
        file_path: "fonts/1754018421082_FN-ANUPAMA.woff2",
        downloadURL:
          "https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754018421082_FN-ANUPAMA.woff2?alt=media&token=a627eaa4-d16b-4ac6-bc6b-b9b4e576be3b",
        createdAt: { _seconds: 1754018424, _nanoseconds: 241000000 },
      },
      {
        id: "vKkLcmwGOiAiVGJiT4Ti",
        name: "space-medium",
        file_path: "fonts/1754019862642_SpaceGrotesk-Medium.woff2",
        downloadURL:
          "https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/fonts%2F1754019862642_SpaceGrotesk-Medium.woff2?alt=media&token=ffc798ab-9cac-4869-9c73-7fd8c02bd158",
        createdAt: { _seconds: 1754019863, _nanoseconds: 700000000 },
      },
    ],
    sponsorAds: [
      {
        id: "I2v1TEXR0Ew6aUyCMTpi",
        name: "da",
        file_path: "sponsor_ads/1753801681865_20250713_151502.jpg",
        downloadURL:
          "https://firebasestorage.googleapis.com/v0/b/mlpeast.firebasestorage.app/o/sponsor_ads%2F1753801681865_20250713_151502.jpg?alt=media&token=62fc866c-3065-4493-9894-5fbd4dfddf90",
        isActive: true,
        uploadedBy: "madeforetech7@gmail.com",
        createdAt: { _seconds: 1753801690, _nanoseconds: 86000000 },
      },
    ],
    malayalamNames: {
      participants: {},
      districts: {},
      programs: {},
      categories: {},
    },
    templateSettings: {
      masterMode: "all",
      categoryAssignments: {
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        10: "",
        11: "",
        12: "",
        13: "",
      },
      sequentialRules: [],
      largeListRule: { threshold: 4, templatePool: [] },
      defaultTemplateId: "",
    },
    sponsorSettings: {
      isEnabled: true,
      rules: [
        {
          id: "rule_1753981759951",
          type: "range",
          sponsorAdId: "I2v1TEXR0Ew6aUyCMTpi",
          createdAt: "2025-07-31T17:09:19.951Z",
          startRank: 101,
          endRank: 110,
        },
      ],
      lastUpdated: { _seconds: 1753981761, _nanoseconds: 652000000 },
    },
    results: {},
  },
};
